In [4]:
import numpy as np
import pandas as pd

# pd.Series

In [5]:
some_list = [1, 3, 5, np.nan, 6, 8]
ser_1 = pd.Series(some_list)
ser_1

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [6]:
ind = ['1st day', '2nd day', '3rd day', '4th day', '5rd day', '6th day']

ser_2 = pd.Series(some_list, index=ind)
ser_2

1st day    1.0
2nd day    3.0
3rd day    5.0
4th day    NaN
5rd day    6.0
6th day    8.0
dtype: float64

In [7]:
ser_2['4th day']

nan

In [8]:
ser_3 = pd.Series(some_list, index=ind, name='Temperature')
ser_3

1st day    1.0
2nd day    3.0
3rd day    5.0
4th day    NaN
5rd day    6.0
6th day    8.0
Name: Temperature, dtype: float64

In [10]:
ser_3[-2::-2]

5rd day    6.0
3rd day    5.0
1st day    1.0
Name: Temperature, dtype: float64

In [11]:
ser_3 > 2

1st day    False
2nd day     True
3rd day     True
4th day    False
5rd day     True
6th day     True
Name: Temperature, dtype: bool

In [12]:
ser_3[ser_3 > 2]

2nd day    3.0
3rd day    5.0
5rd day    6.0
6th day    8.0
Name: Temperature, dtype: float64

In [18]:
arr = pd.Series(range(100))
arr[(arr % 13 == 0) | (arr % 17 == 0)]

0      0
13    13
17    17
26    26
34    34
39    39
51    51
52    52
65    65
68    68
78    78
85    85
91    91
dtype: int64

In [19]:
arr[(arr % 5 == 0) & (arr % 7 == 0)]

0      0
35    35
70    70
dtype: int64

In [20]:
term_1 = pd.Series(np.random.randint(0, 10, 5))
term_2 = pd.Series(np.random.randint(0, 10, 6))

term_1 + term_2

0    11.0
1     7.0
2     4.0
3     6.0
4     9.0
5     NaN
dtype: float64

# pd.DataFrame

In [21]:
some_dict = {'one': pd.Series([1,2,3], index=['a','b','c']),
             'two': pd.Series([1,2,3,4], index=['a','b','c','d']),
             'three': pd.Series([5,6,7,8], index=['a','b','c','d'])}
df = pd.DataFrame(some_dict)
df

one  two  three
a  1.0    1      5
b  2.0    2      6
c  3.0    3      7
d  NaN    4      8

In [30]:
some_mx = np.random.randint(0, 1000, (5, 8))
df = pd.DataFrame(some_mx, 
    index=[f"row {i}" for i in range(5)],
    columns=[f"col {i}" for i in range(8)],
)
df

col 0  col 1  col 2  col 3  col 4  col 5  col 6  col 7
row 0    485     95    721    326    194    516    838    244
row 1    245    870    809    513    765    143    523    799
row 2    233    523    234    390    703    663    702    568
row 3    161     44    864    333    975    540    733    368
row 4    901    757    816    915    526    323    722     59

In [31]:
print(df.values)
print(df.columns)

[[485  95 721 326 194 516 838 244]
 [245 870 809 513 765 143 523 799]
 [233 523 234 390 703 663 702 568]
 [161  44 864 333 975 540 733 368]
 [901 757 816 915 526 323 722  59]]
Index(['col 0', 'col 1', 'col 2', 'col 3', 'col 4', 'col 5', 'col 6', 'col 7'], dtype='object')


In [35]:
df["col 2"]

row 0    721
row 1    809
row 2    234
row 3    864
row 4    816
Name: col 2, dtype: int32

In [37]:
df[["col 2", "col 4"]]

col 2  col 4
row 0    721    194
row 1    809    765
row 2    234    703
row 3    864    975
row 4    816    526

In [43]:
df[-1::-2]

col 0  col 1  col 2  col 3  col 4  col 5  col 6  col 7
row 4    901    757    816    915    526    323    722     59
row 2    233    523    234    390    703    663    702    568
row 0    485     95    721    326    194    516    838    244

In [49]:
df.iloc[1:3, 1:6:2]

col 1  col 3  col 5
row 1    870    513    143
row 2    523    390    663

In [54]:
df.loc[["row 4", "row 0"], ["col 2", "col 5"]]

col 2  col 5
row 4    816    323
row 0    721    516

---

In [68]:
df = pd.DataFrame(
    np.random.randint(0, 1000, (5, 8)),
    columns=[f"col {i}" for i in range(8)],
)
df["new_column"] = np.random.randint(-10, 0, 5).tolist()
df

col 0  col 1  col 2  col 3  col 4  col 5  col 6  col 7  new_column
0    326    452    814    293    904    484    454    361          -7
1    262    824    113    409    977    981    974    557          -9
2    832      6    975    381    351    922    502    611          -4
3    795    623    371     54    409    556    601    660          -9
4    770    747    333    976    497    573    435    546          -7