In [1]:
# consts
N = 10**7
MOD = 1499

In [7]:
# imports
import numpy as np

# Why `numpy`?

In [37]:
%%time
# Casual Python approach: (5.2s)
arr = []
for i in range(N):
    val = i**2+ 5*i - 2
    val %= MOD
    arr.append(val)
assert arr[-1] == 1267

CPU times: total: 4.95 s
Wall time: 4.98 s


1267

In [45]:
%%time
# NumPy approach: (0.2s)
arr = np.arange(N, dtype=np.int64)
arr = (arr**2+ 5*arr - 2) % MOD
assert arr[-1] == 1267

# though if you use
# >  for i in range(N):
# >      ... # do something with arr
# -it'll take the same time as pure python

CPU times: total: 219 ms
Wall time: 222 ms


In [27]:
arr = np.array([2,3,5,7], dtype=np.int64)
print(f"type   = {type(arr)}")
print(f"len    = {len(arr)}")
print(f"dtype  = {arr.dtype}")
print(f"shape  = {arr.shape}")
print(f"nbytes = {arr.nbytes}")

type   = <class 'numpy.ndarray'>
len    = 4
dtype  = int64
shape  = (4,)
nbytes = 32


In [48]:
a = np.linspace(10., 32, 5)
b = np.logspace(0, 3, 5)
print(a)
print(b)
print()
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a * 5)
print(np.sin(a))
print(np.any(a == 22))
print(np.all(a != 0))


[10.  15.5 21.  26.5 32. ]
[   1.            5.62341325   31.6227766   177.827941   1000.        ]

[  11.           21.12341325   52.6227766   204.327941   1032.        ]
[   9.            9.87658675  -10.6227766  -151.327941   -968.        ]
[1.00000000e+01 8.71629054e+01 6.64078309e+02 4.71244044e+03
 3.20000000e+04]
[10.          2.75633309  0.66407831  0.14902045  0.032     ]
[ 50.   77.5 105.  132.5 160. ]
[-0.54402111  0.20646748  0.83665564  0.97935764  0.55142668]
False
True


---

In [57]:
a = 100 + np.arange(1,5)
b = 1000 + np.arange(1,3)
c = 10_000 + np.arange(1,4)
print(a,b,c)
abc = np.hstack((a,b,c))
print(abc)
x, y, z = np.hsplit(abc, [len(a), len(a)+len(b)])
print(x, y, z)

[101 102 103 104] [1001 1002] [10001 10002 10003]
[  101   102   103   104  1001  1002 10001 10002 10003]
[101 102 103 104] [1001 1002] [10001 10002 10003]


---

In [72]:
a = np.arange(1,11)
b = a.copy()
print(a)
print(a[::-1])
print(a[1::2])
a[1::2] = 0
print(a)

b -= 2
print(b)
print(b[[9,9,1,1,6,6,6,4,6,4,6]])


[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]
[ 2  4  6  8 10]
[1 0 3 0 5 0 7 0 9 0]
[-1  0  1  2  3  4  5  6  7  8]
[8 8 0 0 5 5 5 3 5 3 5]


In [86]:
arr = np.linspace(-4*np.pi, 4*np.pi, 100)
res = np.sin(arr)**2 + np.cos(arr)**2
np.all(res - 1. < 0.000000000000001)
# res - 1

array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])