In [1]:
import numpy as np
import random

### 1. Matrix product

In [2]:
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

print(a.ndim)
print(a.shape)

print(a)
print(b)

2
(100, 100)
[[0.4403473  0.49368904 0.77131568 ... 0.28366036 0.45604717 0.07912234]
 [0.15524601 0.74011043 0.40447642 ... 0.7277719  0.35750941 0.54575804]
 [0.1474211  0.40028485 0.6256795  ... 0.54764552 0.11012009 0.72141646]
 ...
 [0.14354242 0.27273265 0.83443564 ... 0.74991319 0.67894111 0.76139995]
 [0.45785524 0.21511717 0.03062787 ... 0.42991428 0.00399278 0.24332086]
 [0.95704725 0.52962391 0.93195829 ... 0.74876342 0.86174949 0.36824659]]
[[0.13271622 0.17987333 0.06445859 ... 0.93323029 0.87117021 0.48035073]
 [0.76977573 0.89208298 0.98382374 ... 0.55253338 0.87239787 0.436636  ]
 [0.77390646 0.87366148 0.31448202 ... 0.62628551 0.76661674 0.32348073]
 ...
 [0.18896093 0.93454328 0.99022153 ... 0.44773395 0.95804219 0.67195319]
 [0.03214656 0.20880685 0.40194629 ... 0.35839896 0.86576647 0.29152132]
 [0.74475299 0.99654621 0.92586503 ... 0.85692351 0.86959383 0.41973765]]


In [3]:
def mult(a, b): # no numpy
    size = len(a[0])
    ans = np.zeros_like(a)
    for i in range(size):
      for j in range(size):
        scal = 0
        for k in range(size):
          scal += a[i][k] * b[k][j]
        ans[i][j] = scal
    return ans

In [4]:
def np_mult(a, b):
    return a @ b

In [5]:
%time M1 = mult(a, b)
%time M2 = np_mult(a, b)

assert np.allclose(np.array(M1), M2)

CPU times: total: 469 ms
Wall time: 468 ms
CPU times: total: 0 ns
Wall time: 16.3 ms


### 2. Vector dot product

In [19]:
N = 10**7
a = np.random.sample((1, N))
a = list(a)[0]
b = np.random.sample((1, N))
b = list(b)[0]
print(a, b)

[0.70758455 0.805586   0.57449034 ... 0.24526614 0.88298613 0.12947273] [0.91494169 0.91904121 0.8403543  ... 0.71608578 0.22107091 0.20402236]


In [11]:
def scalar_product(a, b):
    return sum(x*y for x, y in zip(a, b))

In [21]:
def np_scalar_product(a,b):
    # return np.dot(a, b)
    return a @ b

In [22]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)

assert np.allclose(product_1, product_2)

# pure python is faster 😕 

CPU times: total: 1.97 s
Wall time: 1.97 s
CPU times: total: 62.5 ms
Wall time: 6 ms
